#!/usr/bin/env php
<?php 
$corePath = dirname(__FILE__). '/vendor/gomeetech/dev/src';
if(!file_exists($helper = $corePath.'/helpers/utils.php')) 
    die("\nGomee library was not required!\n\nPlease run:\n\n    composer require gomeetech/dev\n\n");



include $helper;

require_once $corePath.'/dev/load.php';

__call__($argv);